# Generated by Django 2.2.6 on 2020-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Male'), ('2', 'Female')], default=0, max_length=20),
        ),
    ]
