# Generated by Django 2.2.6 on 2020-02-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200214_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='')),
                ('image2', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='extra_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ExtraImages'),
        ),
    ]
