# Generated by Django 2.2.5 on 2020-02-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_image_reper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_reper',
            name='image',
        ),
        migrations.AddField(
            model_name='image_reper',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='image_reper', to='core.Image'),
        ),
    ]
