# Generated by Django 2.2.6 on 2020-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
