# Generated by Django 2.2.6 on 2020-02-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200214_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='image_detail',
            field=models.ManyToManyField(related_name='collect_image', to='core.Image'),
        ),
        migrations.DeleteModel(
            name='Image_reper',
        ),
    ]
