# Generated by Django 2.2.5 on 2020-02-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200214_1608'),
        ('core', '0008_auto_20200216_1658'),
    ]

    operations = [
    ]
