# Generated by Django 2.2.5 on 2020-02-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20200216_1752'),
        ('core', '0009_merge_20200216_1750'),
    ]

    operations = [
    ]
